### ISSUE TITLE
NoMethodError in Product Extraction

### ISSUE THREAD

**Issue by rahulr-codal** [Shopify/shopify_transporter#121]
Getting **NoMethodError** error while doing product extraction.

![product_extraction_error_1](https://user-images.githubusercontent.com/37367175/48539085-3259df80-e8dc-11e8-9e5d-b04ced5c91e6.png)
![product_extraction_error_2](https://user-images.githubusercontent.com/37367175/48539092-35ed6680-e8dc-11e8-8925-ec26eaac6776.png)

shopify_transporter **2.4.2**
Magento **1.9.3.6**
WS-I compliance mode: **No**

**Comment by rahulr-codal** [comment]
I don't know why but when I tried after closing ssh-tunnel, it worked!

**Comment by surajreddy** [comment]
@rahulr-codal thank you for the update - feel free to re-open this if it happens again.
