### ISSUE TITLE
Bundle products are imported without variant options, and with wrong price

### ISSUE THREAD

**Issue by willcodeforfood** [Shopify/shopify_transporter#137]
#### Problem:
Bundle product pricing and variants inconsistent between Shopify and Magento.

#### Steps to Reproduce:
1. Create a bundle product in Magento, with complex variant options (see screenshot)
2. Import said product using the extract + convert + import process
3. Observe the newly created product has no variants, and has the price of one random child product

Side note: I understand that Shopify doesn't natively support complex bundling like Magento does, so I know this isn't an easy problem to solve, and might be outside the scope of what this tool is designed to do.

![selection_212](https://user-images.githubusercontent.com/1639118/52667916-c6d1df00-2ed7-11e9-8654-ae39e429d321.png)
![selection_211](https://user-images.githubusercontent.com/1639118/52667918-c8030c00-2ed7-11e9-8730-799bf97a7812.png)
![selection_210](https://user-images.githubusercontent.com/1639118/52667921-c9cccf80-2ed7-11e9-9885-87335fbaa52b.png)

**Comment by surajreddy** [comment]
@willcodeforfood thank you for reporting this!

You're correct - the extraction script in their current state don't support bundled products right now. 

The code that extracts and maps simple and configurable products is here: https://github.com/Shopify/shopify_transporter/blob/master/lib/shopify_transporter/exporters/magento/product_exporter.rb#L85 - it might be a straightforward change to support bundled products.

**Comment by mimperatore** [comment]
Closing this issue.  Please create a PR to add support for bundled products and we'd be happy to take a look.
