### ISSUE TITLE
shopify_transporter convert command outputs non-unique handles in its product CSV files.

### ISSUE THREAD

**Issue by brianhef** [Shopify/shopify_transporter#138]
#### Problem:

The shopify_transporter convert command outputs non-unique handles on different products in its product CSV files . 

#### Steps to Reproduce:
1. Duplicate a product in the Magento admin and save (Magento 1.x, not sure about 2.x). There are now two products with the same Magento url_key.
2. Run "shopify_transporter extract [...]" including both products.
3. Run shopify_transporter convert on the resulting JSON file.

The resulting CSV file will have the same handle for both the products, and the handle will be the same string as shared url_key of the Magento products.

Magento does not enforce uniqueness on url_key. shopify_transporter cannot reliably use the url_key in unaltered form as a product handle in cases where different products share the same url_key.

**Comment by surajreddy** [comment]
@brianhef thank you for reporting this! Do you have any suggestions for what to do for these cases?

**Comment by brianhef** [comment]
Hello Suraj Reddy,

What I did as a work-around  is edit line 35 of
shopify_transporter-2.5.2/lib/shopify_transporter/pipeline/magento/product/top_level_attributes.rb
. I replaced "url_key" with "url_path", which is generally unique (with
maybe some unusual exceptions). For my case, this caused all my product
handles to end in ".htm", so I removed that extension with a find/replace,
and after that I had Handles that looked mostly like the url_key based
ones, except all handles were unique per product.

Another approach might be to have the shopify_transporter convert process
keep track of the handles add a unique string to any handle that already
exists on another product. I'm new to Ruby and did not see how to implement
this.

Thanks,

Bria Hefferan

**Comment by brianhef** [comment]
What I did as a work-around  is edit line 35 of shopify_transporter-2.5.2/lib/shopify_transporter/pipeline/magento/product/top_level_attributes.rb . I replaced "url_key" with "url_path", which is generally unique (with maybe some unusual exceptions). For my case, this caused all my product handles to end in ".htm", so I removed that extension with a find/replace, and after that I had Handles that looked mostly like the url_key based ones, except all handles were unique per product.

Another approach might be to have the shopify_transporter convert process keep track of the handles add a unique string to any handle that already exists on another product. I'm new to Ruby and did not see how to implement this.

**Comment by brianhef** [comment]
It turns out, some Magento products can have no a url_path in the transporter's .json file. Those products never get a Handle if url_path is used instead of url_key as the basis for the handle.

So, it appears shopify_transporter has no way to reliably set a reasonable unique product handle unless the transporter's convert process gets rewritten to generate one, probably based on url_key and when needed an optional key suffix the shopify_transporter would assign.

This is a big bug, IMO.

**Comment by mimperatore** [comment]
Hi @brianhef, our hope for this gem is that it would be enhanced by the community.  How do you feel about putting a PR together?

**Comment by brianhef** [comment]
Hi Marco,

I looked at the code, and concluded I don't have enough Ruby coding ability
to fix it myself quickly. If I knew how to fix it I would post the code. We
have a hard deadline in a few weeks to replace our Magento site with
Shopify. Right now our plan is to use the correct "url_path" based data
from the transporter_app, and backfill the missing products using other
means.

The Shopify App store description and Help Center pages don't mention the
problem with non-unique product handles. I suppose no one realized it was a
problem. This has been a time-waste
 and setback to our migration, and I wonder how many problems this may have
caused for other migrations, or may cause in the future. Having unique
product handles is a basic requirement.  The problem either should to be
fixed quickly or it should be clearly stated in the help pages and probably
the Shopify App Store page for Shopify Transporter.

**Comment by mimperatore** [comment]
This is not a bug.  We have developed this gem based on some assumptions about how product handles can be derived from Magento data.  We knew it wouldn't necessarily work for everyone, and that's why we have provided the means for developers to be able to override or customize how these mappings are done.   Leveraging this gem to its full capacity does require Ruby programming knowledge, and may require customized rules, in cases like yours.

With regards to the Transporter App's product handle documentation, it is pretty clear [here](https://help.shopify.com/en/manual/migrating-to-shopify/transporter-app/csv-products) that the product handles _must_ be unique.

> The unique identifier for the product. Specify a human-friendly string with no spaces. Usually the handle is the product's title in lowercase with any spaces and special characters replaced by hyphens (-). For example, titan-t-shirt). The handle appears in the URL for the product page in your online store (for example, https://titan.plus/products/titan-t-shirt). This column is required.

**Comment by brianhef** [comment]
Marco, The "shopify_transporter convert" command as supplied does not
reliably generate product csv files with unique handles per Magento
product, so it does not conform to the specifications of the documentation
you quote. Nowhere in the shopify_transporter convert documentation does it
mention this possibility. Why would a customer expect it might not do this
basic essential function correctly?

The README.md  file states "shopify_transporter offers built-in support for
migrations from Magento (version 1), as well as providing support for you
to write your own transformations for other platforms."  (
https://github.com/Shopify/shopify_transporter ). The custom pipeline
stages are presented as ways to extend the shopify_transporter
functionality, and add support for other platforms besides Magento 1.x.

**Comment by mimperatore** [comment]
Thanks for this.  I've created https://github.com/Shopify/shopify_transporter/issues/141 to address the misunderstandings in terms of expectations for this gem.

I do appreciate you providing this feedback, and we'll try to improve this gem in the area you highlighted in the future, but unfortunately we do not have plans to do so in the near future due to other priorities.
