### ISSUE TITLE
Add a command line command to extract data from Magento

### ISSUE THREAD

**Issue by surajreddy** [Shopify/shopify_transporter#14]
Add an `extract` command to the gem that does the following:

Reads these parameters from the config file (or as passed to the command):
- Magento Hostname
- SOAP API Username
- SOAP API Key
- Start Date
- End Date
- Output file
- Type of object (orders/customers/products)

This should incorporate the requirements from #12 and #13:
- return a file that can be used for the convert step of the gem.
- should be resumable.
- accepts a start and end date for the data.

**Comment by jennamsw** [comment]
- Create Gem integrated, tested extraction scripts 
- Pagination on updated scriptes

**Comment by surajreddy** [comment]
This is now part of the newest release: https://github.com/Shopify/shopify_transporter/releases
