### ISSUE TITLE
Case inconsistencies between example orders.csv and official spec

### ISSUE THREAD

**Issue by patspam** [Shopify/shopify_transporter#150]
The official Order CSV format is located [here](https://help.shopify.com/en/manual/migrating-to-shopify/transporter-app/csv-orders). I'm currently writing my own exporter by hand, and have noticed several case inconsistencies between the official example `orders.csv` and the spec:

- `Buyer Accepts Marketing` lists `TRUE` and `FALSE` as values, whereas example uses lowercase. This isn't technically wrong, because this column doesn't say that it's case sensitive, but lots of other columns are, so the inconsistency is unhelpful.
- `Lineitem variant ID` in spec vs. `Lineitem variant id` in example
- `Transaction Location ID` in the spec vs. `Transaction Location Id` in the example 😕 
- Several other `ID` vs. `Id`s

I don't have Shopify Plus, so I'm unable to verify whether any of these will break Transporter at runtime.

**Comment by JordanVerasamy** [comment]
I've gone ahead and changed all of the values you pointed out in the example file to match the casing in the spec. None of them break Transporter at runtime. :)

![image](https://user-images.githubusercontent.com/7587265/86041464-adb9c780-ba13-11ea-94b1-ae82d6b0b16f.png)

Let me know if this helps.
