### ISSUE TITLE
Product tags import issue

### ISSUE THREAD

**Issue by vladimir-tsirulnikov** [Shopify/shopify_transporter#152]
#### Problem:
Product tags are added with quotes

#### Steps to Reproduce:
When creating a CSV file product tags must be wrapped into quotes. So if we need to import tags **tag_1** and **tag_2** we need to add such string to CSV: **"tag_1, tag_2"**, [according the manual](https://help.shopify.com/en/manual/migrating-to-shopify/transporter-app/csv-products). But in Shopify these tags are imported as **"tag_1** and **tag_2"**.

**Comment by surajreddy** [comment]
@vladimir-tsirulnikov we might need to update the documentation for this. You do not need to manually add quotes in the string. Depending on your csv editing software, using `tag_1, tag_2` is sufficient.
