### ISSUE TITLE
Is it possible to get data based on "website_id" rather that "store_id" in magento platform.

### ISSUE THREAD

**Issue by gopalvirat** [Shopify/shopify_transporter#28]
#### Problem:
I want to get data using website_id rather than store_id, is that possible?

**Comment by surajreddy** [comment]
@gopalvirat great question!

Right now this is possible with code changes, and in the future we can make it part of the configuration.

Are you using the main master branch to extract the data, or one of the pull request branches?

If you are using the master branch, you can change the filters we use to fetch this data here:

**Customer:** https://github.com/Shopify/shopify_transporter/blob/master/lib/shopify_transporter/exporters/magento/customer_exporter.rb#L35
**Order:** https://github.com/Shopify/shopify_transporter/blob/master/lib/shopify_transporter/exporters/magento/order_exporter.rb#L37

You can change `item` to anything you need:
```
              item: {
                key: 'website_id',
                value: 1,
              },
```

We are thinking of removing the `store_id` filter and fetching all data - will this work better for your use case?

**Comment by surajreddy** [comment]
Thanks @gopalvirat! 

Are you trying to get all the customers and orders, regardless of the website_id/store_id? Or are you trying to export customers for different websites and stores one at a time?

We're going to make the default export all customers and orders, regardless of the stores. You can see how to do this in the code in this pull request: https://github.com/Shopify/shopify_transporter/pull/31/files

**Comment by surajreddy** [comment]
@gopalvirat we have removed any sort of store_id and website_id filtering, and extract all data in the newest release. Please let us know if this is not ideal or if you run into any other issues with this.
