### ISSUE TITLE
What is the recommended way to export huge data (1Lac plus rows).

### ISSUE THREAD

**Issue by gopalvirat** [Shopify/shopify_transporter#33]
#### Problem:
What is the recommended way to export huge data (1 Lac plus rows).
As the data will be processing line by line, what is the best possible way to handle this.

![shopify_data_export_screengrab](https://user-images.githubusercontent.com/35100967/45532306-351f5200-b811-11e8-9e6c-0bcdea6d58d8.png)

**Comment by JordanVerasamy** [comment]
There's really no way to avoid making 1 API call per customer -- the Magento SOAP API does not support bulk retrieval of customer info. You have to get customer metadata in bulk and then make 1 call per customer to get the detailed data.

Are you getting timeouts? Or is it just slow and you wish it was faster?

**Comment by gopalvirat** [comment]
@JordanVerasamy currently getting no timeouts. It is just slow and I want it to be a little faster.

**Comment by surajreddy** [comment]
@gopalvirat I've created a feature request based on this to retrieve data in parallel: https://github.com/Shopify/shopify_transporter/issues/66
