### ISSUE TITLE
Exporting magento customers using customer.rb gives a raise_invalid_response_error

### ISSUE THREAD

**Issue by chrismarkpd** [Shopify/shopify_transporter#41]
when trying to export magento customers using the customers.rb script, I get the following error:
```
response.rb:90:in raise_invalid_response_error!': Unable to parse response body: (Savon::InvalidResponseError)
```
It seems like the response is coming in as an entire string. I see all the customer information but it is not parsed correctly. Here's a screenshot:

<img width="1293" alt="soap_error" src="https://user-images.githubusercontent.com/19783395/45835014-b4070580-bcbd-11e8-960d-1ee7f2eee24f.png">

It continues to print through every customer until it hits a timeout error: 

```
from /Users/chrismark/.rvm/gems/ruby-2.4.0/gems/savon-2.12.0/lib/savon/response.rb:72:in `find'
	from /Users/chrismark/.rvm/gems/ruby-2.4.0/gems/savon-2.12.0/lib/savon/response.rb:37:in `body'
	from customers.rb:82:in `customer_list'
	from customers.rb:67:in `block in customers_starting_with'
	from /Users/chrismark/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'
	from /Users/chrismark/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/timeout.rb:103:in `timeout'
	from customers.rb:65:in `customers_starting_with'
	from customers.rb:59:in `base_customers'
	from customers.rb:24:in `print_customers'
	from customers.rb:12:in `run'
	from customers.rb:97:in `<main>'
```

orders.rb worked fine and authentication seems to work.

**Comment by chrismarkpd** [comment]
I ran it from the start and there was never a successful customer. It runs for a bit and is just a huge string with customer data. It happens on every run. I don't know if my savon gem is messed up, but it seems to work fine with orders. When I try to export it to a json file, it is blank. I've also tried the export command on customers and it gives me the same result.

**Comment by surajreddy** [comment]
@chrismarkpd what version of Magento are you using? And do you have any extensions installed that might affect the soap output for customers?

**Comment by chrismarkpd** [comment]
We're using 1.9.1.1 . We do have an extension for customers where we extended the customer attributes. I can't remember the name of the extension though.

**Comment by surajreddy** [comment]
Closing this as it's a bit old. @chrismarkpd feel free to re-open or create a new issue if you're still running into this with the current gem version.
