### ISSUE TITLE
Issue with exporting customers with id > 99999 in the extraction-scripts-by-daterange branch

### ISSUE THREAD

**Issue by surajreddy** [Shopify/shopify_transporter#42]
#### Problem:
When there are a lot of customer ids, the customer export script in the `extraction-scripts-by-daterange` is exiting early, for example at customer `99999`.

#### Steps to Reproduce:
List the steps we can take to reproduce the problem:

1. Try exporting customer sets with customers ids greater than 99999.

**Comment by daveshawsa** [comment]
Hi @surajreddy,

I think the ordering of the exported customer IDs is text based rather than numerical which means that if the last_key_id is used to continue a script (as in the case of it existing at 99999 above) cause the duplication of exported customers in subsequent scripts

**Comment by surajreddy** [comment]
This is now fixed with the newest release: https://github.com/Shopify/shopify_transporter/releases
