### ISSUE TITLE
Converting Magento v1.3 Orders only produces name and email fields.

### ISSUE THREAD

**Issue by JayScottDev** [Shopify/shopify_transporter#8]
Converting Magento orders produces only name and email fields.  Our current Magento version is v1.3 and the export was done with SOAP v2 using the method name salesOrderList. I

**Comment by surajreddy** [comment]
@JayScottDev I'm looking into this. I'm sorry you're running into issues!

Any chance you can share the JSON structure of the orders? Looking at the documentation it should be the same across 1.x versions, but perhaps there are differences.

**Comment by surajreddy** [comment]
For reference, this is the format we're expecting the `orders.json` file to be in:
```json
[
  {
    "increment_id": "increment_id-value",
    "created_at": "created_at-value",
    "customer_email": "customer_email-value",
    "customer_firstname": "customer_firstname-value",
    "customer_lastname": "customer_lastname-value",
    "subtotal": "subtotal-value",
    "tax_amount": "1",
    "grand_total": "11",
    "items": {
      "result": {
        "items": {
          "item": [
            {
              "qty_ordered": "qty_ordered-value",
              "sku": "sku-value",
              "name": "name-value",
              "price": "10",
              "tax_amount": "1",
              "tax_percent": "10"
            }
          ]
        },
        "shipping_address": {
          "firstname": "firstname-value",
          "lastname": "lastname-value",
          "telephone": "telephone-value",
          "street": "street-value",
          "city": "city-value",
          "region": "region-value",
          "postcode": "postcode-value",
          "country_id": "country_id-value"
        },
        "billing_address": {
          "firstname": "firstname-value",
          "lastname": "lastname-value",
          "telephone": "telephone-value",
          "street": "street-value",
          "city": "city-value",
          "region": "region-value",
          "postcode": "postcode-value",
          "country_id": "country_id-value"
        }
      }
    }
  }
]
```

**Comment by JayScottDev** [comment]
Interesting, beside the noticeable structural deference it looks like our export doesn't contain line items as well.   Here is an example of the export we received:

`[
  {
    "increment_id": "value",
    "store_id": "value",
    "created_at": "value",
    "updated_at": "value",
    "customer_id": "value",
    "tax_amount": "value",
    "shipping_amount": "value",
    "discount_amount": "value",
    "subtotal": "value",
    "grand_total": "value",
    "total_paid": "value",
    "total_refunded": "value",
    "total_qty_ordered": "value",
    "total_canceled": "value",
    "base_tax_amount": "value",
    "base_shipping_amount": "value",
    "base_discount_amount": "value",
    "base_subtotal": "value",
    "base_grand_total": "value",
    "base_total_paid": "value",
    "base_total_canceled": "value",
    "billing_address_id": "value",
    "billing_firstname": "value",
    "billing_lastname": "value",
    "shipping_address_id": "value",
    "shipping_firstname": "value",
    "shipping_lastname": "value",
    "billing_name": "value",
    "shipping_name": "value",
    "store_to_base_rate": "value",
    "store_to_order_rate": "value",
    "base_to_global_rate": "value",
    "base_to_order_rate": "value",
    "weight": "value",
    "store_name": "value",
    "status": "value",
    "state": "value",
    "global_currency_code": "value",
    "base_currency_code": "value",
    "store_currency_code": "value",
    "order_currency_code": "value",
    "shipping_description": "value",
    "customer_email": "value",
    "customer_firstname": "value",
    "customer_lastname": "value",
    "customer_group_id": "value",
    "customer_is_guest": "value",
    "order_id": "value",
    "protect_code": "value",
    "base_discount_canceled": "value",
    "base_shipping_canceled": "value",
    "base_shipping_tax_amount": "value",
    "base_subtotal_canceled": "value",
    "base_tax_canceled": "value",
    "discount_canceled": "value",
    "shipping_canceled": "value",
    "shipping_tax_amount": "value",
    "subtotal_canceled": "value",
    "tax_canceled": "value",
    "paypal_ipn_customer_notified": "value",
    "base_shipping_discount_amount": "value",
    "base_subtotal_incl_tax": "value",
    "base_total_due": "value",
    "shipping_discount_amount": "value",
    "subtotal_incl_tax": "value",
    "total_due": "value",
    "total_item_count": "value",
    "shipping_incl_tax": "value",
    "base_shipping_incl_tax": "value",
    "firstname": "value",
    "lastname": "value",
    "telephone": "value",
    "postcode": "value"
  }
]`

**Comment by surajreddy** [comment]
@JayScottDev thank you! The structure does make a difference (the cli tool is expecting a json array).

We're working on adding scripts to make it easier to extract data using the SOAP calls. These should be available soon, but a work in progress version is available as a PR: https://github.com/Shopify/shopify_transporter/pull/7/files#diff-a9ca578d0c747c672bb7000b48bfa6caR36

We make an extra call to `sales_order_info` to get the line items information: https://devdocs.magento.com/guides/m1x/api/soap/sales/salesOrder/sales_order.info.html

You can try running the scripts from the PR, or mimic this logic to get the line items for each order:
```
  orders << order.merge('items' => items_for(order))
  ...
  def items_for(order)
    soap_client.call(
      :sales_order_info,
      message: {
        session_id: soap_session_id,
        order_increment_id: order[:increment_id],
      }
    ).body[:sales_order_info_response]
  end
```

**Comment by reckerswartz** [comment]
@surajreddy  I have gone through PR.
`ruby orders.rb`
savon is raising an error
```
/gems/savon-2.12.0/lib/savon/response.rb:85:in `raise_soap_and_http_errors!': (SOAP-ENV:Server) Allowed memory size of 2147483648 bytes exhausted (tried to allocate 83 bytes) (Savon::SOAPFault)
	from /home/aventum/.rvm/gems/ruby-2.4.0@transporter/gems/savon-2.12.0/lib/savon/response.rb:14:in `initialize'
	from /home/aventum/.rvm/gems/ruby-2.4.0@transporter/gems/savon-2.12.0/lib/savon/operation.rb:72:in `new'
	from /home/aventum/.rvm/gems/ruby-2.4.0@transporter/gems/savon-2.12.0/lib/savon/operation.rb:72:in `create_response'
	from /home/aventum/.rvm/gems/ruby-2.4.0@transporter/gems/savon-2.12.0/lib/savon/operation.rb:58:in `call'
	from /home/aventum/.rvm/gems/ruby-2.4.0@transporter/gems/savon-2.12.0/lib/savon/client.rb:36:in `call'
	from orders.rb:28:in `base_orders'
	from orders.rb:19:in `orders'
	from orders.rb:9:in `run'
	from orders.rb:48:in `<main>'

```
I have searched for it but cannot find the solution and tried on multiple machines

Do you have any idea about it?

**Comment by surajreddy** [comment]
@reckerswartz I believe the issue you are seeing is because you are running out of memory when running the script - do you know roughly how many orders are on the magento instance you are trying to use? 

We are working on an updated version of the scripts that involves paginating and retrieving a smaller set of orders instead of all of them, that should help with this issue.

**Comment by reckerswartz** [comment]
@surajreddy nearly 5000 orders. do you know any solution for now until script available?

**Comment by surajreddy** [comment]
@reckerswartz I created a separate issue for the problems you are facing so we can keep this ticket focused on the original issue. I'll respond to you there.

**Comment by surajreddy** [comment]
@JayScottDev how are you doing with this? Were you able to get the right fields extracted?
