### ISSUE TITLE
If the order contains a simple product, its parent product will occupy a row in the conversion CSV too

### ISSUE THREAD

**Issue by zliu1020** [Shopify/shopify_transporter#91]
Simple product in order will occupy two lines as their parent product shows up too. Shopify will treat them as two products instead of one. The solution is to remove the parent product from CSV.

In Magento:
![screen shot 2018-10-16 at 2 24 18 pm](https://user-images.githubusercontent.com/21313470/47038512-abd0a780-d14f-11e8-9e8e-32ecf951e840.png)
In CSV:
<img width="759" alt="screen shot 2018-10-16 at 2 24 34 pm" src="https://user-images.githubusercontent.com/21313470/47038497-a3786c80-d14f-11e8-927d-e6cee4505a85.png">

**Comment by JordanVerasamy** [comment]
Update: We decided to handle this in the transformation step instead of the extraction step. Closed the previous PRs and implementing some similar logic in the order attributes accumulator instead.
